Initial CI support
reitzig/ltx2any pull request #121
Opened 2022-02-25 14:26 UTC by koppor

This is a setup to solve https://github.com/reitzig/ltx2any/issues/116.

>     1. Run tests against
>     * Ruby versions 2.3, 2.4, 2.5;

Simple execution done with these versions. Real LaTeXing test only Ruby 2.5, because even that is outdated now (see https://gitlab.alpinelinux.org/alpine/aports/-/issues/13555#note_218801)

>     * GNU/Linux and TeXlive;

Done via https://github.com/reitzig/texlive-docker

>     * macOS and MacTeX (?);

Note done; one could follow the steps at https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388.
 
>     * Windows and MiKTeX/proTeXt (?).

With Docker hard to do https://github.com/actions/virtual-environments/issues/1143#issuecomment-651670345; even though MiKTeX offers a Docker image.

>     2. Build and deploy docs (if applicable).

Not done.

>     3. Build and deploy gem (if commit tagged).

Not done. Could be done with a Google Cloud Platform action: https://andrewm.codes/blog/automating-ruby-gem-releases-with-github-actions/

When this update is in place, the output on GitHub is as follows:

![grafik](https://user-images.githubusercontent.com/1366654/155731174-04deb06f-75c7-45cf-ae99-e3fbc1910d20.png)

I don't know whether this works with `chew` (https://github.com/reitzig/ltx2any/tree/gemification), but I think, this can be adapted when the development is continued.

Side comment: The motivation to look into this is that installing ruby on a Docker image is less a hazzle than ensuring that `makeglossaries` is called at the correct place in other build tools. [cluttex](https://github.com/minoki/cluttex) was my choice after `latexmk`, because it is written in lua, which is available in LaTeX installations. However, it does trigger `bibtex` when a `.bib` file is updated. -- Maybe, a stand-alone binary can be generated in the future so that one does not need to play around with ruby versions.

2024-03-06 19:57 UTC, koppor commented
I updated the PR to include macOS, Windows, and some more ruby versions.

Maybe, the number of ruby versions can be reduced?

I also have issues with Ruby on Windows:

```
Run ruby ltx2any.rb test/test.tex
[ltx2any] Copying files to tmp ... Done
pdflatex: security risk: running with elevated privileges
[ltx2any] PdfLaTeX(1) running ... Error
[ltx2any] Error: uninitialized constant PdfLaTeX::TexLogParser
          See test.err for details.
```

2024-03-09 15:26 UTC, reitzig requested changes
Let's drop support for Ruby <3.1.

All of 2.x are EOL, and 3.0 is about to be: https://endoflife.date/ruby

2024-03-09 15:26 UTC, reitzig commented
Can't seem to update the PR myself; will add suggestions.

2024-03-09 15:27 UTC, reitzig commented on .github/workflows/check.yml
> +        ruby: [ '2.3', '2.4', '2.5', '3.0', '3.1', '3.2', '3.3' ]
```suggestion
        ruby: [ '3.1', '3.2', '3.3' ]
```

2024-03-09 15:27 UTC, reitzig commented on .github/workflows/check.yml
> +        ruby: [ '2.3', '2.4', '2.5', '3.0', '3.1', '3.2', '3.3' ]
```suggestion
        ruby: [ '3.1', '3.2', '3.3' ]
```

2024-03-09 15:27 UTC, reitzig commented on README.md
> + * Ruby 2.3, 2.4., or 2.5 and
```suggestion
 * Ruby 3.1 or higher, and
```

2024-03-09 15:29 UTC, reitzig approved these changes

2024-03-09 15:30 UTC, merged

2024-03-09 16:44 UTC, koppor commented
Note that the Windows MiKTeX install cannot be performance increased, because Caching for `choco install` is still an open issue: https://github.com/chocolatey/choco/issues/2134

2024-03-09 16:45 UTC, koppor commented
Any improvements to the MiKTeX workflow should be contributed back to https://stackoverflow.com/a/76953318/873282.